spring:
  cloud:
     aws:
       credentials:
         access-key: ${AWS_ACCESS_KEY}
         secret-key: ${AWS_SECRET_KEY}
       region:
         static: ${AWS_REGION}
       s3:
         bucket: ${S3_BUCKET_NAME}
       sqs:
         queue-url: ${SQS_URL}
  application:
    name: streamer-api
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

# application-local.properties
ffmpeg.path: /usr/bin/ffmpeg
ffprobe.path: /usr/bin/ffprobe

sqs:
  transcoder:
    queue-url: ${SQS_TRANSCODER_URL}
    max-retry: ${MAX_RETRY}



logging:
  level:
    io.awspring.cloud.sqs: DEBUG
