version: "3.8"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=sujay.shanbhag999@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - app-network

  streamer-api:
    image: ghcr.io/sujayshanbhag/streamer-api:APP_VERSION
    container_name: streamer-api
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - /opt/tinyflix/secrets:/opt/tinyflix/secrets:ro
    labels:
      - "traefik.enable=true"
      # HTTPS — all requests go to API
      - "traefik.http.routers.api.rule=Host(`api.tinyflix.shanbhag.dev`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=le"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      # HTTP → HTTPS redirect
      - "traefik.http.routers.api-http.rule=Host(`api.tinyflix.shanbhag.dev`)"
      - "traefik.http.routers.api-http.entrypoints=web"
      - "traefik.http.routers.api-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"


  streamer-ui:
    image: ghcr.io/sujayshanbhag/streamer-ui:UI_VERSION
    container_name: streamer-ui
    restart: unless-stopped
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=Host(`tinyflix.shanbhag.dev`)"
      - "traefik.http.routers.ui.entrypoints=websecure"
      - "traefik.http.routers.ui.tls.certresolver=le"
      - "traefik.http.services.ui.loadbalancer.server.port=80"
      - "traefik.http.routers.ui-http.rule=Host(`tinyflix.shanbhag.dev`)"
      - "traefik.http.routers.ui-http.entrypoints=web"
      - "traefik.http.routers.ui-http.middlewares=https-redirect"

  streamer-transcoder:
    image: ghcr.io/sujayshanbhag/streamer-transcoder:APP_VERSION
    container_name: streamer-transcoder
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge

volumes:
  letsencrypt:
